### PR TITLE
Add 'nil' support for unsetting variable(s)

### PR DESCRIPTION
**Pull request by mstalfoort**
## Usecase

According to Codekit help (https://incident57.com/codekit/help.html#kit) "Nil Variables" is supported, yet by using the command line version and setting a variable to "nil" will output that exact value in the HTML end result.

### CODE REVIEW

**Comment by jeremyworboys** [comment]
The diff looks fine. If you add a test case for the change I'll merge.

**Comment by mstalfoort** [comment]
cool, can you help me out a bit on writing the test, i don't have much experience with it yet

**Comment by fatso83** [comment]
@mstalfoort : just look at how it is [done](https://github.com/jeremyworboys/node-kit/blob/develop/test/node-kit.test.js), then do the developer boogie:
- copy
- paste
- modify
- run

If `npm test` runs afterwards you are good to go :dancers: . Basically just add a kit file and the expected output to the `test/fixtures` dir and make `kit` compile it.

**Comment by mstalfoort** [comment]
updated, can you please check again

**Comment by jeremyworboys** [comment]
Looks great. Thanks!

**Pull request merged**
